[build]
target = "x86_64-unknown-none"
#rustflags = ["-C", "link-arg=-T.cargo/kernel.ld"]
[target.'cfg(target_os = "none")']
rustflags = ["-C", "link-arg=--image-base=0xffffffff80000000"]
runner = "cargo qemu"